package com.example.batterymonitor.ui.dashboard

object BatteryTips {
    val list = listOf(
        "Reduce screen brightness manually to a comfortable level.",
        "Enable adaptive brightness for automatic screen adjustment.",
        "Activate dark mode or dark themes, especially on OLED displays.",
        "Set your screen timeout to the shortest practical duration (15-30 seconds).",
        "Disable the Always-On Display feature to save power.",
        "Lower your screen's refresh rate from 120Hz to 60Hz if not needed.",
        "Keep your battery charge level ideally between 30% and 80%.",
        "Avoid letting your battery completely drain to 0%.",
        "Refrain from constantly charging your phone all the way to 100%.",
        "Unplug your device once it reaches 80-90% charge to minimize stress.",
        "Charge your phone in short, frequent top-ups throughout the day.",
        "Always use the original or certified charging cables and adapters.",
        "Protect your phone from extreme heat sources like direct sunlight.",
        "Avoid exposing your phone to freezing temperatures for long periods.",
        "Do not use your phone for intensive tasks while it's charging.",
        "Enable your phone's built-in Battery Saver or Power Saving mode.",
        "Turn on the Adaptive Battery feature in your device settings.",
        "Close applications running in the background that you are not using.",
        "Review and restrict background app permissions for better efficiency.",
        "Disable 'Allow background use' for specific power-hungry apps.",
        "Turn off location services when you don't need them.",
        "Revoke location access for individual apps that do not require it.",
        "Disable Wi-Fi connectivity when you are not actively using it.",
        "Turn off Bluetooth when no devices are connected or in use.",
        "Disable mobile data when Wi-Fi is available or not needed.",
        "Use Airplane mode in areas with poor cellular signal.",
        "Limit or disable 5G access if it's excessively draining your battery.",
        "Turn off NFC (Near Field Communication) if you rarely use it.",
        "Disable keyboard sounds and haptic (vibration) feedback.",
        "Reduce the number of non-essential notifications you receive.",
        "Deactivate voice assistant hotword detection if unused.",
        "Remove or sign out of unused accounts from your device.",
        "Uninstall applications that you no longer use regularly.",
        "Avoid installing third-party 'battery optimizer' or cleaner apps.",
        "Regularly monitor your battery usage statistics to identify draining apps.",
        "Utilize your phone's built-in battery optimization features.",
        "Let the Android system manage background apps naturally.",
        "Disable auto-sync for email and photos if not critical.",
        "Choose a static, predominantly dark or black wallpaper.",
        "Avoid using animated, live, or constantly changing wallpapers.",
        "Lower your screen resolution if your device supports it.",
        "Occasionally turn off your phone overnight to give the battery a rest.",
        "Periodically perform a full charge-discharge cycle to calibrate.",
        "Limit continuous GPS navigation when battery is low.",
        "Minimize frequent use of your phone as a Wi-Fi hotspot.",
        "Avoid tasks that process large amounts of data in the background.",
        "Restart your phone regularly to clear temporary software glitches.",
        "Keep your Android operating system updated to the latest version.",
        "Ensure all your installed applications are kept updated.",
        "Disable unused system apps that might run in the background.",
        "Avoid using your phone in very humid environments while charging.",
        "Remove thick cases while charging if the device gets too warm.",
        "Use 'Focus Mode' to reduce distractions and screen-on time.",
        "Limit high-performance gaming sessions to when you are plugged in.",
        "Check for apps with excessive 'Wake Locks' in battery settings.",
        "Prefer Wi-Fi over Cellular for downloads whenever possible.",
        "Turn off 'Scanning for nearby devices' in connection settings.",
        "Disable auto-update for apps over mobile data.",
        "Keep the 'Protect Battery' feature enabled if your phone has it.",
        "Avoid keeping your phone under a pillow while charging."
    )
}
